config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :users, :only => [:new, :create, :index, :show]

  resources :bags

  resources :pokemons

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  #I didn't try to delete these, even though I have the resources above.
  get '/bags/show/:id' => 'bags#show'
  get '/bags/index' => 'bags#index'
  get '/bags/:id/edit' => 'bags#edit'

  get '/users/show/:id' => 'users#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attack.rb
class Attack < ApplicationRecord
  has_and_belongs_to_many :pokemons
end

app/models/bag.rb
class Bag < ApplicationRecord
  belongs_to :user, :optional => true
  has_and_belongs_to_many :pokemons
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_and_belongs_to_many :bags
  has_and_belongs_to_many :attacks

  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bags
  has_many :pokemons, :through => :bags
  has_secure_password
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to root_path unless @current_user.present? && @current_user.admin
  end

  ######################gets the list of all the pokemon and their names
  def get_pokemon
    @api_list = PokeApi.get(pokemon: {limit: 1200, offset: 0})
    @available_pokemon = []
    @api_list.results.each do |n|
      @available_pokemon << n.name
    end
  end

end

app/controllers/bags_controller.rb
class BagsController < ApplicationController
  before_action :check_for_login

  def index
    @bags = @current_user.bags.all
  end

  def new
    @bag = Bag.new
    @pokemons = Pokemon.all
  end

  def create
    bag = Bag.create bag_params
    @current_user.bags << bag ########user now has a bag associated with their acocunt
    redirect_to root_path
  end

  def edit
    @bag = Bag.find params[:id]
  end

  def update
    bag = Bag.find params[:id]
    bag.update bag_params
    redirect_to bag
  end

  def show
    @bag = Bag.find params[:id]
  end

  def destroy
    bag = Bag.find params[:id]
    bag.destroy
    redirect_to bags_path
  end

  private
  def bag_params
    params.require(:bag).permit(:title, :pokemon_ids => [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home ############# Selecting a random pokemon with the PokeApi for the game
    return redirect_to login_path unless @current_user.present?
    @api_list = PokeApi.get(pokemon: {limit: 1200, offset: 0})
    @rand_pokemon1 = @api_list.results.sample
  end

end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :get_pokemon

  def index
    @pokemons = Pokemon.all
  end

  def new
    @pokemon = Pokemon.new
  end

  def create ##You can only create a pokemon that exists in the PokeApi
    @pokemon = Pokemon.new pokemon_params
    if @available_pokemon.include? @pokemon[:name]
      @pokemon.save
      redirect_to pokemons_path
    else render :new
    end
  end

  def edit #####################Blocker: Assigning attacks to pokemon only in the user's bag.
    @pokemon = Pokemon.find params[:id]
    @attacks = @pokemon.attacks.all
  end

  def update
    pokemon = Pokemon.find params[:id]
    pokemon.update pokemon_params
    redirect_to bags_path
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    url = "https://pokeapi.co/api/v2/pokemon/#{ @pokemon.name }/"
    @info = HTTParty.get url;
    #Blurb about the pokemon, because it was too hard to access the 100 different attacks each pokemon has
    @character_url = @info["species"]["url"]
    url2 = @character_url
    @info2 = HTTParty.get url2;
    @blurb = @info2["flavor_text_entries"][0]["flavor_text"]
  end

  private
  def pokemon_params
    params.require(:pokemon).permit(:name, :attack)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :name => params[:name]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid username"
      redirect_to login_path
    end
  end


  def destroy
      session[:user_id] = nil
      redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to bags_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bags_helper.rb
module BagsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bags/_form.html.erb
<%= form_for @bag do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :placeholder => 'Favourite starter Pokémon bag' %>
  <br>
  <br>

  <% Pokemon.all.each do |pokemon| %>
    <%= check_box_tag "bag[pokemon_ids][]", pokemon.id, @bag.pokemon_ids.include?(pokemon.id) %>
    <%= pokemon.name %><br/>
  <% end %>
  <br>
  <%= f.submit %>
<% end %>

app/views/bags/edit.html.erb
<h1>Edit <%= @bag.title %></h1>

<%= render :partial => 'form' %>

app/views/bags/index.html.erb
<h1>Here are all your inventories, <%= @current_user.name %></h1>

<% @bags.each do |bag| %>
  <%= link_to bag.title, bag %>
<% end %>



<br>
<br>
<br>
<%= link_to "New Inventory", new_bag_path %>

app/views/bags/new.html.erb
<h1>New Inventory</h1>

<%= render :partial => 'form' %>

app/views/bags/show.html.erb
<h1><%= @bag.title %></h1>

<!-- User's bag menu where you can add more pokemon for the battle and change their attacks -->
<% @bag.pokemons.each do |pokemon| %>
  <%= link_to image_tag("https://files.pokefans.net/sprites/xy/animationen/#{ pokemon.name }.gif"), pokemon %>
  <br>
<% end %>

<div class="bagControls">
  <%= link_to 'Edit Bag', edit_bag_path(@bag) %>
  <%= button_to 'Delete Bag', @bag, :method => 'delete' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home page</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/assets/session.css">
  </head>

  <body>
    <nav>
      <%= link_to 'Home', root_path %>
      <% if @current_user.present? %>
        <% if @current_user.admin? %>
          <%= link_to 'Users', users_path %>
        <% end %>
        <%= link_to "Pokédex", pokemons_path %>
        <%= link_to "Inventories", bags_path %>
        <%= link_to "Log out #{ @current_user.name }", login_path, :method => 'delete' %>
      <% else %>
        <%= link_to 'Sign up', new_user_path %>
        <%= link_to 'Login', login_path %>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Home</h1>

<% if @current_user.present? %>
  <h2>
    Welcome to your personal Pokédex, <%= @current_user.name %>.
  </h2>
  <br>
  <p>
    Here you can add Pokémon to the your personal Pokédex database and create a groups of favourites.
  </p>
<% end %>

app/views/pokemons/_form.html.erb
<%= form_for @pokemon do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "Add Pokemon to Pokedex" %>
<% end %>

app/views/pokemons/index.html.erb
<h1>All Pokemons</h1>

  <% @pokemons.each do |pokemon| %>
    <div class="index">
        <%= link_to image_tag("https://files.pokefans.net/sprites/xy/animationen/#{ pokemon.name }.gif", :class => "indexed"), pokemon %>
    </div>
  <% end %>


  <br>
  <br>
  <br>
  <%= link_to "Add Pokémon", new_pokemon_path %>

app/views/pokemons/new.html.erb
<h1>New Pokemon</h1>

<%= render :partial => 'form' %>

app/views/pokemons/show.html.erb
<h1><%= @pokemon.name %></h1>

<%= image_tag "https://files.pokefans.net/sprites/xy/animationen/#{ @pokemon.name }.gif" %>
<br>
<p><%= @blurb %></p>

app/views/session/new.html.erb
<div class="pokemon">
  <%= image_tag "/pokemonLogo.png", :class => "logo"%>
</div>

<h1>Sign In</h1>

<% if flash[:error].present? %>
  <p class="error">
    <%= flash[:error] %>
  </p>
<% end %>

<div class="controls">
    <%= form_tag login_path do %>
      <%= label_tag :name %>
      <%= text_field_tag :name %>
      <%= label_tag :password %>
      <%= password_field_tag :password %>
      <br>
      <%= submit_tag "Sign in" %>
    <% end %>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
  <p><%= user.name %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Sign up!" %>
<% end %>